### ISSUE TITLE
Bug in `fname` formatting

### ISSUE THREAD

**Issue by wbenoit26** [alecgunny/deepclean-demo#2]
As it stands, I get the following error trying to run data generation:
```
File "/opt/deepclean/projects/data/data/cli.py", line 52, in main
    fname = "{prefix}-{start}-{end}.hdf5".format(prefix, **args)
KeyError: 'prefix'
```

This is resolved by changing the line to `fname = "{prefix}-{start}-{end}.hdf5".format(prefix=prefix, **args)`

**Comment by alecgunny** [comment]
Ahhh duh great catch, clearly I've been too lazy to let the fetch code run all the way through. Fixing now
