### ISSUE TITLE
Error with GPU specification in README instructions

### ISSUE THREAD

**Issue by wbenoit26** [alecgunny/deepclean-demo#3]
When running the training command in the README as-is, I get the following error:

`law run: error: argument --gpus: expected one argument`

I worked around it by manually setting `--gpus 0`, but I haven't been able to work out why `--gpus $GPU_INDEX` isn't doing the same thing

**Comment by alecgunny** [comment]
ahh in order for the env variable to get passed into the poetry shell that gets launched implicitly, it needs to be `export`'d (or defined inline at the start of the command). Just defining a variable only defines it in your current shell.

**Comment by wbenoit26** [comment]
Ahhh, that makes sense
